name: Veracode - SCA scan hit a problem

run-name: Veracode - SCA scan hit a problem - ${{ github.event.client_payload.repository.name }}

on:
  repository_dispatch:
    types: [veracode-sca-error]
    
jobs:
  register:
    runs-on: ubuntu-latest
    steps:
    - uses: veracode/Veracode-github-app@aws-ecs-dynamodb
      with:
        callback_url: ${{ github.event.client_payload.callback_url }}
        sha: ${{ github.event.client_payload.sha }}
        branch: ${{ github.event.client_payload.branch }}
        run_id: ${{ github.run_id }}
        repository_owner: ${{ github.event.client_payload.repository.owner }}
        repository_name: ${{ github.event.client_payload.repository.name }}
        event_type: ${{ github.event.client_payload.event_type }}
        enforce: true
       
  veracode-sca-error:
    needs: [register]
    runs-on: ubuntu-latest
    name: Veracode - SCA scan hit a problem 

    steps:
      - name: Display error message
        run: |
          echo "Veracode SCA scan faced a problem."
          echo "Please contact your Veracode administrator for more information."
          echo "If you are a Veracode administrator, please contact Veracode support."
          echo "Veracode SCA scan faced a problem." > error.txt
          echo "Please contact your Veracode administrator for more information." >> error.txt
          echo "If you are a Veracode administrator, please contact Veracode support." >> error.txt
      - name: save results file
        uses: actions/upload-artifact@v3
        with:
          name: veracode-error
          path: error.txt

