name: Veracode - SAST/SCA Not Supported Repository

run-name: Veracode - SAST/SCA Not Supported Repository - ${{ github.event.client_payload.repository.name }}

on:
  repository_dispatch:
    types: [veracode-not-supported]
    
jobs:
  create-checks-run:
    name: Create Checks Run
    runs-on: ubuntu-latest
    steps:
    - uses: LouisBrunner/checks-action@v1.6.2
      name: Create Checks Run
      id: create_checks_run
      with:
        token: ${{ github.event.client_payload.token }}
        repo: ${{ github.event.client_payload.repository.full_name }}
        sha: ${{ github.event.client_payload.sha }}
        name: ${{ env.name || github.workflow }}
        status: completed
        conclusion: success
        output: |
          {"summary":"Veracode SAST/SCA is not supported for this repository.\nPlease contact your Veracode administrator for more information.\nIf you are a Veracode administrator, please contact Veracode support."}
